//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domjenak
    {
        public int id_domjenak { get; set; }
        public int id_klijent { get; set; }
        public Nullable<int> id_invertar { get; set; }
        public Nullable<int> kolicina { get; set; }
        public System.DateTime datum { get; set; }
        public decimal vrijeme1 { get; set; }
        public Nullable<decimal> vrijeme2 { get; set; }
        public Nullable<int> brojLjudi { get; set; }
        public Nullable<int> brojKonobara { get; set; }
        public decimal ukupnaCijena { get; set; }
        public decimal kapara { get; set; }
        public string klijent { get; set; }
        public string invertar { get; set; }
    
        public virtual Invertar Invertar1 { get; set; }
        public virtual Klijent Klijent1 { get; set; }
    }
}
